-- SQLite

-- Criar a tabela EMPLOYEES (Funcionários)

CREATE TABLE EMPLOYEES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR (100) NOT NULL,
    PHONE VARCHAR (100) NOT NULL,
    CONTRACT_DATE VARCHAR (100) NOT NULL,
    POSITION_ID INTEGER NOT NULL
    );