-- SQLite

-- Criar a tabela CARS (Carros)

CREATE TABLE CARS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR (200) NOT NULL,
    YEAR INTEGER NOT NULL,
    COLOR VARCHAR (100) NOT NULL,
    KM INTEGER NOT NULL,
    STATUS VARCHAR (100) NOT NULL,
    BRAND_ID INTEGER NOT NULL,
    MODEL_ID INTEGER NOT NULL
);