-- SQLite

-- Criar a tabela LOCATIONS (Locações)

CREATE TABLE LOCATIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    TOTAL INTEGER NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,
    CAR_ID INTEGER NO NULL,	
    EMPLOYEE_ID INTEGER NOT NULL
);