-- SQLite

-- Consulta capaz de exibir todas as locações realizadas, entre as datas “2022-05-20” a “2022-12-25”

SELECT LOCATIONS.ID,
       LOCATIONS.START_DATE,
       LOCATIONS.END_DATE,
       LOCATIONS.TOTAL,
       CUSTOMERS.NAME,
       CUSTOMERS.LASTNAME,
       CARS.NAME,
       EMPLOYEES.NAME FROM LOCATIONS

JOIN CUSTOMERS ON (LOCATIONS.CUSTOMER_ID = CUSTOMERS.ID)
JOIN EMPLOYEES ON (LOCATIONS.EMPLOYEE_ID = EMPLOYEES.ID)
JOIN CARS ON (LOCATIONS.CAR_ID = CARS.ID)

WHERE LOCATIONS.START_DATE BETWEEN '2022-05-20' AND '2022-12-25';